### ISSUE TITLE
This plugin work when app is in background?

### ISSUE THREAD

**Issue by cinder92** [syarul/react-native-android-location#4]
Thats my question :)

**Comment by AmeerHamzaRiaz** [comment]
I also want to use in background ? did you try it ???

**Comment by syarul** [comment]
I haven't test it or have time for it, but its nothing to do with this plugin since its written as minimal way to get location from your android device, but what you should do is to update the plugin java code: https://github.com/syarul/react-native-android-location/blob/master/src/main/java/com/syarul/rnalocation/RNALocationModule.java by including a service to make it always run on the background.

Create a service:
```java
public class YourService extends Service {

    @Nullable
    @Override
    public IBinder onBind(Intent intent) {
        return null;
    }

    @Override
    public int onStartCommand(Intent intent, int flags, int startId) {
        // do your jobs here
        return super.onStartCommand(intent, flags, startId);
    }
}
```
Create an Application class and start your service:

```java
public class App extends Application {

    @Override
    public void onCreate() {
        super.onCreate();

        startService(new Intent(this, YourService.class));
    }
}
```
